title: V&N Team

navbar: ./config/navbar.yml

page:
  index: ./config/index.yml
  achievements: ./config/achievements.md
  members: ./config/members.yml
  join: ./config/join.md

footer:
  - Copyright (c) [V&N Team](:link-normal:!https://vnteam.cn)
  -
    - '[萌ICP备XXXXXXXX号](https://icp.gov.moe/)'
    - '[浙公网安备XXXXXXXXXXXXXXX](https://beian.mps.gov.cn/#/query/webSearch?code=XXXXXXXXXXXXXXX)'

